version: "2"
services:
  nginx:
    image: trambar-nginx-dev
    ports:
      - 80:80
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../../trambar/client/www:/var/www/trambar/client
    depends_on:
      - data_server
      - websocket_notifier
  postgres:
    image: trambar-postgres
    ports:
      - 5432:5432
    volumes:
      - ../tmp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
  schema_manager:
    image: trambar-node-dev
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, schema-manager.js ]
    depends_on:
      - postgres
  webdav_server:
    image: trambar-node-dev
    ports:
      - 8000:8000
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, webdav-server.js ]
    depends_on:
      - postgres
  data_server:
    image: trambar-node-dev
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, data-server.js ]
    depends_on:
      - postgres
  auth_manager:
    image: trambar-node-dev
#    ports:
#      - 9229:9229
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
#    command: [ nodemon, --inspect, auth-manager.js ]
    command: [ nodemon, auth-manager.js ]    
    depends_on:
      - postgres
  media_server:
    image: trambar-node-dev
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
      - ../tmp/media:/var/cache/media
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, media-server.js ]
    depends_on:
      - postgres
  websocket_notifier:
    image: trambar-node-dev
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, websocket-notifier.js ]
    depends_on:
      - postgres
  live_data_invalidator:
    image: trambar-node-dev
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, live-data-invalidator.js ]
    depends_on:
      - postgres
  live_data_updater:
    image: trambar-node-dev
    volumes:
      - ../../trambar/backend/src:/opt/trambar/backend/src
      - ../../trambar/common/src:/opt/trambar/common/src
    environment:
      - NODE_PATH=/opt/trambar/backend/node_modules:/opt/trambar/backend/src:/opt/trambar/backend/src/lib:/opt/trambar/common/src
      - NODE_ENV=development
      - DEPLOYMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trambar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    command: [ nodemon, live-data-updater.js ]
    depends_on:
      - postgres
