version: "2"
volumes:
  web_cache:
services:
  # Nginx web server
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media
      - web_cache:/var/cache/nginx
      - ./snakeoil:/etc/ssl/snakeoil
    depends_on:
      - data_server
      - event_notifier
  # PostgreSQL database manager
  postgres:
    image: trambar/trambar-postgres
    ports:
      - 5432:5432
    volumes:
      - ${TRAMBAR_DATABASE_FOLDER}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
  schema_manager:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
      - DATABASE_ADMIN_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
      - DATABASE_CLIENT_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
      - DATABASE_AUTH_PASSWORD=${TRAMBAR_DATABASE_AUTH_PASSWORD}
    command: [ node, --experimental-modules, schema-manager.mjs ]
    depends_on:
      - postgres
  # WebDAV server
  webdav_server:
    image: trambar-node-dev
    ports:
      - 8000:8000
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
    command: [ node, --experimental-modules, webdav-server.mjs ]
    depends_on:
      - postgres
  # Web page handler (Node.js)
  www_handler:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/admin/www:/opt/trambar/admin/www
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
      - ../../../trambar/client/www:/opt/trambar/client/www
      - web_cache:/var/cache/nginx
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, --experimental-modules, www-handler.mjs ]
    depends_on:
      - postgres
  # Data server (Node.js)
  data_server:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, --experimental-modules, data-server.mjs ]
    depends_on:
      - postgres
  # Admin data server (Node.js)
  admin_data_server:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
      - ADMIN_GUEST_MODE=1
    command: [ node, --experimental-modules, data-server.mjs ]
    depends_on:
      - postgres
  # Authentication manager (Node.js)
  session_manager:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
      - ${TRAMBAR_HTPASSWD_FOLDER}:/etc/trambar
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=auth_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_AUTH_PASSWORD}
      - HTPASSWD_PATH=/etc/trambar/${TRAMBAR_HTPASSWD_NAME}
      - ADMIN_GUEST_MODE=1
    command: [ node, --experimental-modules, session-manager.mjs ]
    depends_on:
      - postgres
  # Media server (Node.js)
  media_server:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/media:/opt/trambar/backend/media
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, --experimental-modules, media-server.mjs ]
    depends_on:
      - postgres
  # WebSocket Notifier (Node.js)
  event_notifier:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/client/src/locales:/opt/trambar/backend/src/locales
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, --experimental-modules, event-notifier.mjs ]
    depends_on:
      - postgres
  # Live Data Invalidator (Node.js)
  live_data_invalidator:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, --experimental-modules, live-data-invalidator.mjs ]
    depends_on:
      - postgres
  # Live Data Updater (Node.js)
  live_data_updater:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    command: [ node, --experimental-modules, live-data-updater.mjs ]
    depends_on:
      - postgres
  # GitLab Adapter (Node.js)
  gitlab_adapter:
    image: trambar-node-dev
    volumes:
      - ../../../trambar/backend/src:/opt/trambar/backend/src
      - ../../../trambar/client/src/locales:/opt/trambar/backend/src/locales
      - ../../../trambar/common/src:/opt/trambar/backend/src/lib/common
      - /var/cache/git-cache:/var/cache/gitlab
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
    command: [ node, --experimental-modules, gitlab-adapter.mjs ]
    depends_on:
      - postgres
